name: Keep Render App Awake

on:
  schedule:
    - cron: "*/30 * * * *" 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (optional, if ping.js is in repo)
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Create ping script
        run: |
          echo "const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.goto('https://luminouz-18x0.onrender.com', { waitUntil: 'networkidle2' });
            await browser.close();
          })();" > ping.js
      - name: Run ping script
        run: node ping.js
